CREATE DATABASE MOEDA_ESTUDANTIL; 


CREATE TABLE USUARIO(
  LOGIN int(10) NOT NULL,
  NOME varchar(60) NOT NULL,
  SENHA VARCHAR(12) NOT NULL,
  PRIMARY KEY(LOGIN)
) ENGINE=InnoDB;

CREATE TABLE INSTITUICAO(
ID INT UNSIGNED AUTO_INCREMENT  NOT NULL,
NOME VARCHAR(60) NOT NULL,
PRIMARY KEY(ID)
) ENGINE=InnoDB;

CREATE TABLE ALUNO(
 CPF INT(11) NOT NULL,
 EMAIL VARCHAR(40) NOT NULL, 
 RG INT(8) NOT NULL,
 ENDERECO VARCHAR(60) NOT NULL,
 CURSO VARCHAR(20) NOT NULL,
 MOEDAS INT(10),
 LOGIN_USUARIO int(10) NOT NULL,   
 ID_INSTITUICAO INT UNSIGNED NOT NULL,
 PRIMARY KEY(CPF),/* CHAVE PRIMARIA*/
 foreign key(LOGIN_USUARIO) references USUARIO(LOGIN),/*CHAVE ESTRANGEIRA*/
 foreign key(ID_INSTITUICAO) references INSTITUICAO(ID)/*CHAVE ESTRANGEIRA*/
 )ENGINE=InnoDB;

CREATE TABLE PROFESSOR(
 CPF INT(11) NOT NULL,
 MOEDAS INT(10),  
 DEPARTAMENTO VARCHAR(20) NOT NULL,
 LOGIN_USUARIO int(10) NOT NULL,
 ID_INSTITUICAO INT UNSIGNED NOT NULL,   
 PRIMARY KEY(CPF),/* CHAVE PRIMARIA*/
 foreign key(LOGIN_USUARIO) references USUARIO(LOGIN),/*CHAVE ESTRANGEIRA*/
 foreign key(ID_INSTITUICAO) references INSTITUICAO(ID)/*CHAVE ESTRANGEIRA*/
 )ENGINE=InnoDB;


CREATE TABLE EMPRESA(
 CNPJ VARCHAR(14) NOT NULL,
 NOME VARCHAR(60),
 LOGIN_USUARIO int(10) NOT NULL,
 PRIMARY KEY(CNPJ),/* CHAVE PRIMARIA*/
 foreign key(LOGIN_USUARIO) references USUARIO(LOGIN)/*CHAVE ESTRANGEIRA*/
 )ENGINE=InnoDB;

 CREATE TABLE VANTAGEM(
 ID INT UNSIGNED AUTO_INCREMENT  NOT NULL,
 CUSTO_MOEDAS INT(10) NOT NULL,
 FOTO VARCHAR(60),
 NOME varchar(60) NOT NULL,
 DESCRICAO varchar(60) NOT NULL,
 CNPJ_EMPRESA VARCHAR(14) NOT NULL,    
 PRIMARY KEY(ID),/* CHAVE PRIMARIA*/
 foreign key(CNPJ_EMPRESA) references EMPRESA(CNPJ)/*CHAVE ESTRANGEIRA*/
 )ENGINE=InnoDB;

/*Insere uma instituicao no banco*/
INSERT INTO `instituicao`(`ID`, `NOME`) VALUES (1,'PUC Minas');

/*Insere um usuario no banco*/
INSERT INTO `usuario`(`LOGIN`, `NOME`, `SENHA`) VALUES (123,'Ana','123');
INSERT INTO `usuario`(`LOGIN`, `NOME`, `SENHA`) VALUES (456,'Joana','123');
INSERT INTO `usuario`(`LOGIN`, `NOME`, `SENHA`) VALUES (789,'Joao','123');
INSERT INTO `usuario`(`LOGIN`, `NOME`, `SENHA`) VALUES (098,'Janio','123');

/*Insere um professor no banco*/
INSERT INTO `professor`(`CPF`, `MOEDAS`, `DEPARTAMENTO`, `LOGIN_USUARIO`, `ID_INSTITUICAO`) VALUES (123456789,1000,'ICEI',123,1);
INSERT INTO `professor`(`CPF`, `MOEDAS`, `DEPARTAMENTO`, `LOGIN_USUARIO`, `ID_INSTITUICAO`) VALUES (123456783,1000,'ICEI',456,1);
INSERT INTO `professor`(`CPF`, `MOEDAS`, `DEPARTAMENTO`, `LOGIN_USUARIO`, `ID_INSTITUICAO`) VALUES (123456781,1000,'ICEI',789,1);
INSERT INTO `professor`(`CPF`, `MOEDAS`, `DEPARTAMENTO`, `LOGIN_USUARIO`, `ID_INSTITUICAO`) VALUES (123456782,1000,'ICEI',098,1);








